apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: linkedevents-api
  description: Linked Events API
spec:
  type: openapi
  lifecycle: unknown
  owner: platta
  definition: |
    openapi: 3.0.0
    info:
      title: Linked Events API
      version: 1.0.0
    servers:
      - url: 'https://api.yourdomain.com/v1'

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: linkedevents
  title: Linked Events backend
  annotations:
    github.com/project-slug: City-of-Helsinki/linkedevents
    dev.azure.com/project-repo: linkedevents/linkedevents-pipelines
    quay.io/repository-slug: hki-kanslia-linkedevents/linkedevents-api
    backstage.io/kubernetes-id: linkedevents
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: platta
  providesApis:
    - linkedevents-api
