apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: linkedevents
  annotations:
    github.com/project-slug: City-of-Helsinki/linkedevents
    backstage.io/topology: 'enabled'
spec:
  type: other2
  lifecycle: unknown
  owner: platta
