apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: linkedevents-system
  title: Linked Events
  description: Event management system
spec:
  owner: platta

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: linkedevents-api
  description: Linked Events API
spec:
  type: openapi
  lifecycle: unknown
  owner: platta
  system: linkedevents-system
  definition: |
    openapi: 3.0.0
    info:
      title: Linked Events API
      version: 1.0.0
    servers:
      - url: 'https://api.yourdomain.com/v1'

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: linkedevents
  title: Linked Events backend
  description: Linked Events backend
  tags:
    - backend
  annotations:
    github.com/project-slug: City-of-Helsinki/linkedevents
    dev.azure.com/project-repo: linkedevents/linkedevents-pipelines
    quay.io/repository-slug: hki-kanslia-linkedevents/linkedevents-api
    backstage.io/kubernetes-id: linkedevents
    backstage.io/techdocs-ref: dir:.
    sentry.io/project-slug: linkedevents-api
    sonarqube.org/project-key: City-of-Helsinki_linkedevents
    jira/project-key: LINK
spec:
  type: other
  lifecycle: unknown
  owner: platta
  providesApis:
    - linkedevents-api
  system: linkedevents-system
  dependsOn:
    - resource:default/kulke
    - resource:default/lippupiste
    - resource:default/espoo-linkedevents

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kulke
  title: External Kulttuurikeskus Elis service
  description: |
    The Kulttuurikeskus Elis system is an external system that provides event data
    for cultural events. The events are fetched periodically to Linked Events.
  tags:
    - external
spec:
  type: external-service
  owner: external-systems

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lippupiste
  title: External Lippupiste service
  description: |
    The Lippupiste system is an external system that provides ticketing and event data
    for cultural events. The events are fetched periodically to Linked Events.
  tags:
    - external
spec:
  type: external-service
  owner: external-systems

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kulke
  title: External Kulttuurikeskus Elis service
  description: |
    The Kulttuurikeskus Elis system is an external system that provides event data
    for cultural events. The events are fetched periodically to Linked Events.
  tags:
    - external
spec:
  type: external-service
  owner: external-systems

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: espoo-linkedevents
  title: External Espoo Linked Events service
  description: |
    The Espoo Linked Events system is an external system that provides event data
    for cultural events. The events are fetched periodically to Linked Events.
  tags:
    - external
  link:
    - title: Espoo Linked Events API URL
      url: https://api.espoo.fi/events/
spec:
  type: external-service
  owner: external-systems

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: external-systems
  description: External systems not owned by internal teams
spec:
  type: team
  profile:
    displayName: External Systems
