[tool.black]
line-length = 88 # Black's default value
target-version = ["py39"]

[tool.isort]
profile = "black"
py_version = 39
atomic = true
order_by_type = false
extend_skip_glob = ["*migrations*"]

[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I"
]
extend-per-file-ignores = { "*migrations*" = ["E501"] }
pycodestyle.max-line-length = 120
