name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  common-ci:
    name: Common CI
    uses: tuomas777/.github/.github/workflows/ci-django-api.yml@reusable_workflow_precommit
    secrets: inherit
    with:
      python-version: 3.9
      database-type: postgis
      additional-checks: |
        python manage.py spectacular --lang en --validate --fail-on-warn --api-version v1
        python manage.py makemigrations --dry-run --check
